Repository wildfirepy/wildfirepy, pull requests merged in 2020-05, with the labels that each got.

#23 Adds code of conduct and contributors list.
  CODE_OF_CONDUCT.rst
  MANIFEST.in
  contributors.json
Labels: No Changelog Required

#31 Fix `issues page` link in README.md
  README.md
Labels: No Changelog Required, documentation

#34 Updates name of acknowledgement.md and removes CoC.
  Acknowledgement.md
  CODE_OF_CONDUCT.rst
Labels: No Changelog Required

#51 Adds VIIRS client
  changelog/51.feature.rst
  wildfirepy/net/tests/test_modis.py
  wildfirepy/net/tests/test_viirs.py
  wildfirepy/net/usgs/__init__.py
  wildfirepy/net/usgs/modis.py
  wildfirepy/net/usgs/usgs_downloader.py
  wildfirepy/net/usgs/viirs.py
  wildfirepy/net/util/usgs.py
Labels: enhancement, feature, urgent

#58 Added abhijeet in contributors
  contributors.json
Labels: No Changelog Required
